import {ActivityIcon} from '@sanity/icons'
import {defineArrayMember, defineField, defineType} from 'sanity'

/**
 * A learner's progress, keyed by their Clerk user id (AGENTS.md §8).
 *
 * This is app state, not authored content. It is written only by the server
 * route at `app/api/progress/route.ts` using the write token — the browser
 * never writes it, and no author edits it in the Studio (§5, §7). It is kept
 * apart from the read-only catalog content the pages render, and excluded from
 * the search agent's content scope so learner data never reaches the LLM (§10).
 *
 * One document per learner rather than one per learner-course: My Learning
 * needs every course's state at once, and a single document means one fetch
 * instead of one query per course, and one lookup per write.
 *
 * `_id` is generated by Sanity. The Clerk id lives in `userId` and every lookup
 * queries that field — per the sanity-best-practices global rule against
 * deterministic ids for ordinary documents.
 *
 * Lessons and courses are stored as ids, not slugs. A slug is editable content;
 * an author renaming one must not silently un-complete a learner's lesson.
 */
export const progress = defineType({
  name: 'progress',
  title: 'Learner Progress',
  type: 'document',
  icon: ActivityIcon,
  // Written by the app, never by hand. Studio edits would be clobbered and
  // could corrupt a learner's history.
  readOnly: true,
  fields: [
    defineField({
      name: 'userId',
      title: 'Clerk User ID',
      type: 'string',
      description: 'The learner this record belongs to. One document per user.',
      validation: (rule) =>
        rule.required().custom(async (userId, context) => {
          if (!userId) return true
          const client = context.getClient({apiVersion: '2026-08-27'})
          const id = context.document?._id?.replace(/^drafts\./, '')
          const existing = await client.fetch(
            `count(*[_type == "progress" && userId == $userId && _id != $id])`,
            {userId, id},
          )
          return existing === 0 || 'A progress record already exists for this user'
        }),
    }),
    defineField({
      name: 'completedLessons',
      title: 'Completed Lessons',
      type: 'array',
      description: 'Lesson ids the learner has finished.',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'lastPositions',
      title: 'Last Positions',
      type: 'array',
      description: 'Where the learner left off in each lesson.',
      of: [
        defineArrayMember({
          type: 'object',
          name: 'lastPosition',
          fields: [
            defineField({name: 'lessonId', type: 'string', validation: (r) => r.required()}),
            defineField({
              name: 'seconds',
              type: 'number',
              validation: (r) => r.required().min(0),
            }),
          ],
          preview: {
            select: {title: 'lessonId', subtitle: 'seconds'},
          },
        }),
      ],
    }),
    defineField({
      name: 'enrolledCourses',
      title: 'Started Courses',
      type: 'array',
      description:
        'Course ids the learner has opened. Kept separate from completions so a ' +
        'course that has been reset to 0% still appears on My Learning.',
      of: [defineArrayMember({type: 'string'})],
    }),
    defineField({
      name: 'removedCourses',
      title: 'Removed Courses',
      type: 'array',
      description:
        'Course ids the learner hid from My Learning. Hiding only — completion ' +
        'data is deliberately preserved, so reopening the course restores it.',
      of: [defineArrayMember({type: 'string'})],
    }),
  ],
  preview: {
    select: {title: 'userId', completed: 'completedLessons'},
    prepare({title, completed}) {
      const count = Array.isArray(completed) ? completed.length : 0
      return {
        title: title || 'Unknown learner',
        subtitle: `${count} lesson${count === 1 ? '' : 's'} completed`,
      }
    },
  },
})
